apiVersion: v1
kind: Pod
metadata:
  name: jupyter-evidently
  labels:
    app: jupyter-evidently
spec:
  containers:
    - name: jupyter
      image: peterwolf/jupyter:evidently
      ports:
        - name: jupyter
          containerPort: 8888
          protocol: TCP
   