apiVersion: v1
kind: ConfigMap
metadata:
  name: drifter-envs
  namespace: airflow
data:
  MLFLOW_TRACKING_URI: http://mlflow-minio.mlflow.svc
  MLFLOW_S3_ENDPOINT_URL: http://mlflow-tracking.mlflow.svc