apiVersion: v1
kind: ConfigMap
metadata:
  name: drifter-envs
  namespace: airflow
data:
  DRIFTER_URL: http://drifter-svc.default.svc/api/v1/data
  REFERENCE_DF_PATH: datasets/reference.csv
  MLFLOW_TRACKING_URI: http://mlflow-tracking.mlflow.svc
  MLFLOW_S3_ENDPOINT_URL: http://mlflow-minio.mlflow.svc

