git:
  dags:
    enabled: true
    repositories:
    - repository: "https://github.com/peter-and-wolf/otus_mlops_k8s_dags2.git"
      branch: "main"
      name: ""
      path: "dags"

worker:
  extraEnvVarsSecret: "drifter-secret"
  extraEnvVarsCM: "drifter-envs"
  
  # Указываем, куда будет монтироваться volume
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/
  
  # Указываем, где взять volume, чтобы примонтировать 
  # его по координатам из предыдущей секции 
  extraVolumes:
    - name: requirements
      configMap:
        name: requirements
